server:
  port: 8080

# Mongo
spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/
      auto-index-creation: true
      authentication-database: admin
      database: hexagonal-architecture

# Clients
rafael:
  clients:
    address:
      url: "http://localhost:8082/api/v1/addresses"

kafka:
  url: "localhost:9092"
  groups:
    rafael:
      name: "rafael"
